import { Cidade } from '../interfaces/cidades';

export const CIDADES: Cidade[] = [
  {	id:	1	,	name:	'Abatia - PR'	}	,
  {	id:	2	,	name:	'Adrianopolis - PR'	}	,
  {	id:	3	,	name:	'Agudos do Sul - PR'	}	,
  {	id:	4	,	name:	'Almirante Tamandare - PR'	}	,
  {	id:	5	,	name:	'Altamira do Parana - PR'	}	,
  {	id:	6	,	name:	'Altania - PR'	}	,
  {	id:	7	,	name:	'Alto Parana - PR'	}	,
  {	id:	8	,	name:	'Alto Piquiri - PR'	}	,
  {	id:	9	,	name:	'Alvorada do Sul - PR'	}	,
  {	id:	10	,	name:	'Amapora - PR'	}	,
  {	id:	11	,	name:	'Ampere - PR'	}	,
  {	id:	12	,	name:	'Anahy - PR'	}	,
  {	id:	13	,	name:	'Andira - PR'	}	,
  {	id:	14	,	name:	'Angulo - PR'	}	,
  {	id:	15	,	name:	'Antonina - PR'	}	,
  {	id:	16	,	name:	'Antonio Olinto - PR'	}	,
  {	id:	17	,	name:	'Apucarana - PR'	}	,
  {	id:	18	,	name:	'Arapongas - PR'	}	,
  {	id:	19	,	name:	'Arapoti - PR'	}	,
  {	id:	20	,	name:	'Arapua - PR'	}	,
  {	id:	21	,	name:	'Araruna - PR'	}	,
  {	id:	22	,	name:	'Araucaria - PR'	}	,
  {	id:	23	,	name:	'Ariranha do Ivai - PR'	}	,
  {	id:	24	,	name:	'Assai - PR'	}	,
  {	id:	25	,	name:	'Assis Chateaubriand - PR'	}	,
  {	id:	26	,	name:	'Astorga - PR'	}	,
  {	id:	27	,	name:	'Atalaia - PR'	}	,
  {	id:	28	,	name:	'Balsa Nova - PR'	}	,
  {	id:	29	,	name:	'Bandeirantes - PR'	}	,
  {	id:	30	,	name:	'Barbosa Ferraz - PR'	}	,
  {	id:	31	,	name:	'Barra do Jacare - PR'	}	,
  {	id:	32	,	name:	'Barracao - PR'	}	,
  {	id:	33	,	name:	'Bela Vista da Caroba - PR'	}	,
  {	id:	34	,	name:	'Bela Vista do Paraiso - PR'	}	,
  {	id:	35	,	name:	'Bituruna - PR'	}	,
  {	id:	36	,	name:	'Boa Esperanca do Iguacu - PR'	}	,
  {	id:	37	,	name:	'Boa Esperanca - PR'	}	,
  {	id:	38	,	name:	'Boa Ventura de Sao Roque - PR'	}	,
  {	id:	39	,	name:	'Boa Vista da Aparecida - PR'	}	,
  {	id:	40	,	name:	'Bocaiuva do Sul - PR'	}	,
  {	id:	41	,	name:	'Bom Jesus do Sul - PR'	}	,
  {	id:	42	,	name:	'Bom Sucesso do Sul - PR'	}	,
  {	id:	43	,	name:	'Bom Sucesso - PR'	}	,
  {	id:	44	,	name:	'Borrazopolis - PR'	}	,
  {	id:	45	,	name:	'Braganey - PR'	}	,
  {	id:	46	,	name:	'Brasilandia do Sul - PR'	}	,
  {	id:	47	,	name:	'Cafeara - PR'	}	,
  {	id:	48	,	name:	'Cafelandia - PR'	}	,
  {	id:	49	,	name:	'Cafezal do Sul - PR'	}	,
  {	id:	50	,	name:	'California - PR'	}	,
  {	id:	51	,	name:	'Cambara - PR'	}	,
  {	id:	52	,	name:	'Cambe - PR'	}	,
  {	id:	53	,	name:	'Cambira - PR'	}	,
  {	id:	54	,	name:	'Campina Grande do Sul - PR'	}	,
  {	id:	55	,	name:	'Campina da Lagoa - PR'	}	,
  {	id:	56	,	name:	'Campina do Simao - PR'	}	,
  {	id:	57	,	name:	'Campo Bonito - PR'	}	,
  {	id:	58	,	name:	'Campo Largo - PR'	}	,
  {	id:	59	,	name:	'Campo Magro - PR'	}	,
  {	id:	60	,	name:	'Campo Mourao - PR'	}	,
  {	id:	61	,	name:	'Campo do Tenente - PR'	}	,
  {	id:	62	,	name:	'Candido de Abreu - PR'	}	,
  {	id:	63	,	name:	'Candoi - PR'	}	,
  {	id:	64	,	name:	'Cantagalo - PR'	}	,
  {	id:	65	,	name:	'Capanema - PR'	}	,
  {	id:	66	,	name:	'Capitao Leonidas Marques - PR'	}	,
  {	id:	67	,	name:	'Carambei - PR'	}	,
  {	id:	68	,	name:	'Carlopolis - PR'	}	,
  {	id:	69	,	name:	'Cascavel - PR'	}	,
  {	id:	70	,	name:	'Castro - PR'	}	,
  {	id:	71	,	name:	'Catanduvas - PR'	}	,
  {	id:	72	,	name:	'Centenario do Sul - PR'	}	,
  {	id:	73	,	name:	'Cerro Azul - PR'	}	,
  {	id:	74	,	name:	'Ceu Azul - PR'	}	,
  {	id:	75	,	name:	'Chopinzinho - PR'	}	,
  {	id:	76	,	name:	'Cianorte - PR'	}	,
  {	id:	77	,	name:	'Cidade Gaucha - PR'	}	,
  {	id:	78	,	name:	'Clevelandia - PR'	}	,
  {	id:	79	,	name:	'Colombo - PR'	}	,
  {	id:	80	,	name:	'Colorado - PR'	}	,
  {	id:	81	,	name:	'Congonhinhas - PR'	}	,
  {	id:	82	,	name:	'Conselheiro Mairinck - PR'	}	,
  {	id:	83	,	name:	'Contenda - PR'	}	,
  {	id:	84	,	name:	'Corbelia - PR'	}	,
  {	id:	85	,	name:	'Cornelio Procopio - PR'	}	,
  {	id:	86	,	name:	'Coronel Domingos Soares - PR'	}	,
  {	id:	87	,	name:	'Coronel Vivida - PR'	}	,
  {	id:	88	,	name:	'Corumbatai do Sul - PR'	}	,
  {	id:	89	,	name:	'Cruz Machado - PR'	}	,
  {	id:	90	,	name:	'Cruzeiro do Iguacu - PR'	}	,
  {	id:	91	,	name:	'Cruzeiro do Oeste - PR'	}	,
  {	id:	92	,	name:	'Cruzeiro do Sul - PR'	}	,
  {	id:	93	,	name:	'Cruzmaltina - PR'	}	,
  {	id:	94	,	name:	'Curitiba - PR'	}	,
  {	id:	95	,	name:	'Curiuva - PR'	}	,
  {	id:	96	,	name:	'Diamante d Oeste - PR'	}	,
  {	id:	97	,	name:	'Diamante do Norte - PR'	}	,
  {	id:	98	,	name:	'Diamante do Sul - PR'	}	,
  {	id:	99	,	name:	'Dois Vizinhos - PR'	}	,
  {	id:	100	,	name:	'Douradina - PR'	}	,
  {	id:	101	,	name:	'Doutor Camargo - PR'	}	,
  {	id:	102	,	name:	'Doutor Ulysses - PR'	}	,
  {	id:	103	,	name:	'Eneas Marques - PR'	}	,
  {	id:	104	,	name:	'Engenheiro Beltrao - PR'	}	,
  {	id:	105	,	name:	'Entre Rios do Oeste - PR'	}	,
  {	id:	106	,	name:	'Esperanca Nova - PR'	}	,
  {	id:	107	,	name:	'Espigao Alto do Iguacu - PR'	}	,
  {	id:	108	,	name:	'Farol - PR'	}	,
  {	id:	109	,	name:	'Faxinal - PR'	}	,
  {	id:	110	,	name:	'Fazenda Rio Grande - PR'	}	,
  {	id:	111	,	name:	'Fenix - PR'	}	,
  {	id:	112	,	name:	'Fernandes Pinheiro - PR'	}	,
  {	id:	113	,	name:	'Figueira - PR'	}	,
  {	id:	114	,	name:	'Flor da Serra do Sul - PR'	}	,
  {	id:	115	,	name:	'Florai - PR'	}	,
  {	id:	116	,	name:	'Floresta - PR'	}	,
  {	id:	117	,	name:	'Florestopolis - PR'	}	,
  {	id:	118	,	name:	'Florida - PR'	}	,
  {	id:	119	,	name:	'Formosa do Oeste - PR'	}	,
  {	id:	120	,	name:	'Foz do Iguacu - PR'	}	,
  {	id:	121	,	name:	'Foz do Jordao - PR'	}	,
  {	id:	122	,	name:	'Francisco Alves - PR'	}	,
  {	id:	123	,	name:	'Francisco Beltrao - PR'	}	,
  {	id:	124	,	name:	'General Carneiro - PR'	}	,
  {	id:	125	,	name:	'Godoy Moreira - PR'	}	,
  {	id:	126	,	name:	'Goioere - PR'	}	,
  {	id:	127	,	name:	'Goioxim - PR'	}	,
  {	id:	128	,	name:	'Grandes Rios - PR'	}	,
  {	id:	129	,	name:	'Guaira - PR'	}	,
  {	id:	130	,	name:	'Guairaca - PR'	}	,
  {	id:	131	,	name:	'Guamiranga - PR'	}	,
  {	id:	132	,	name:	'Guapirama - PR'	}	,
  {	id:	133	,	name:	'Guaporema - PR'	}	,
  {	id:	134	,	name:	'Guaraci - PR'	}	,
  {	id:	135	,	name:	'Guaraniacu - PR'	}	,
  {	id:	136	,	name:	'Guarapuava - PR'	}	,
  {	id:	137	,	name:	'Guaraquecaba - PR'	}	,
  {	id:	138	,	name:	'Guaratuba - PR'	}	,
  {	id:	139	,	name:	'Honorio Serpa - PR'	}	,
  {	id:	140	,	name:	'Ibaiti - PR'	}	,
  {	id:	141	,	name:	'Ibema - PR'	}	,
  {	id:	142	,	name:	'Ibipora - PR'	}	,
  {	id:	143	,	name:	'Icaraima - PR'	}	,
  {	id:	144	,	name:	'Iguaracu - PR'	}	,
  {	id:	145	,	name:	'Iguatu - PR'	}	,
  {	id:	146	,	name:	'Imbau - PR'	}	,
  {	id:	147	,	name:	'Imbituva - PR'	}	,
  {	id:	148	,	name:	'Inacio Martins - PR'	}	,
  {	id:	149	,	name:	'Inaja - PR'	}	,
  {	id:	150	,	name:	'Indianopolis - PR'	}	,
  {	id:	151	,	name:	'Ipiranga - PR'	}	,
  {	id:	152	,	name:	'Ipora - PR'	}	,
  {	id:	153	,	name:	'Iracema do Oeste - PR'	}	,
  {	id:	154	,	name:	'Irati - PR'	}	,
  {	id:	155	,	name:	'Iretama - PR'	}	,
  {	id:	156	,	name:	'Itaguaje - PR'	}	,
  {	id:	157	,	name:	'Itaipulandia - PR'	}	,
  {	id:	158	,	name:	'Itambaraca - PR'	}	,
  {	id:	159	,	name:	'Itambe - PR'	}	,
  {	id:	160	,	name:	'Itapejara d Oeste - PR'	}	,
  {	id:	161	,	name:	'Itaperucu - PR'	}	,
  {	id:	162	,	name:	'Itauna do Sul - PR'	}	,
  {	id:	163	,	name:	'Ivai - PR'	}	,
  {	id:	164	,	name:	'Ivaipora - PR'	}	,
  {	id:	165	,	name:	'Ivate - PR'	}	,
  {	id:	166	,	name:	'Ivatuba - PR'	}	,
  {	id:	167	,	name:	'Jaboti - PR'	}	,
  {	id:	168	,	name:	'Jacarezinho - PR'	}	,
  {	id:	169	,	name:	'Jaguapita - PR'	}	,
  {	id:	170	,	name:	'Jaguariaiva - PR'	}	,
  {	id:	171	,	name:	'Jandaia do Sul - PR'	}	,
  {	id:	172	,	name:	'Janiopolis - PR'	}	,
  {	id:	173	,	name:	'Japira - PR'	}	,
  {	id:	174	,	name:	'Japura - PR'	}	,
  {	id:	175	,	name:	'Jardim Alegre - PR'	}	,
  {	id:	176	,	name:	'Jardim Olinda - PR'	}	,
  {	id:	177	,	name:	'Jataizinho - PR'	}	,
  {	id:	178	,	name:	'Jesuitas - PR'	}	,
  {	id:	179	,	name:	'Joaquim Tavora - PR'	}	,
  {	id:	180	,	name:	'Jundiai do Sul - PR'	}	,
  {	id:	181	,	name:	'Juranda - PR'	}	,
  {	id:	182	,	name:	'Jussara - PR'	}	,
  {	id:	183	,	name:	'Kalore - PR'	}	,
  {	id:	184	,	name:	'Lapa - PR'	}	,
  {	id:	185	,	name:	'Laranjal - PR'	}	,
  {	id:	186	,	name:	'Laranjeiras do Sul - PR'	}	,
  {	id:	187	,	name:	'Leopolis - PR'	}	,
  {	id:	188	,	name:	'Lidianopolis - PR'	}	,
  {	id:	189	,	name:	'Lindoeste - PR'	}	,
  {	id:	190	,	name:	'Loanda - PR'	}	,
  {	id:	191	,	name:	'Lobato - PR'	}	,
  {	id:	192	,	name:	'Londrina - PR'	}	,
  {	id:	193	,	name:	'Luiziana - PR'	}	,
  {	id:	194	,	name:	'Lunardelli - PR'	}	,
  {	id:	195	,	name:	'Lupionopolis - PR'	}	,
  {	id:	196	,	name:	'Mallet - PR'	}	,
  {	id:	197	,	name:	'Mambore - PR'	}	,
  {	id:	198	,	name:	'Mandaguacu - PR'	}	,
  {	id:	199	,	name:	'Mandaguari - PR'	}	,
  {	id:	200	,	name:	'Mandirituba - PR'	}	,
  {	id:	201	,	name:	'Manfrinopolis - PR'	}	,
  {	id:	202	,	name:	'Mangueirinha - PR'	}	,
  {	id:	203	,	name:	'Manoel Ribas - PR'	}	,
  {	id:	204	,	name:	'Marechal Candido Rondon - PR'	}	,
  {	id:	205	,	name:	'Maria Helena - PR'	}	,
  {	id:	206	,	name:	'Marialva - PR'	}	,
  {	id:	207	,	name:	'Marilandia do Sul - PR'	}	,
  {	id:	208	,	name:	'Marilena - PR'	}	,
  {	id:	209	,	name:	'Mariluz - PR'	}	,
  {	id:	210	,	name:	'Maringa - PR'	}	,
  {	id:	211	,	name:	'Mariopolis - PR'	}	,
  {	id:	212	,	name:	'Maripa - PR'	}	,
  {	id:	213	,	name:	'Marmeleiro - PR'	}	,
  {	id:	214	,	name:	'Marquinho - PR'	}	,
  {	id:	215	,	name:	'Marumbi - PR'	}	,
  {	id:	216	,	name:	'Matelandia - PR'	}	,
  {	id:	217	,	name:	'Matinhos - PR'	}	,
  {	id:	218	,	name:	'Mato Rico - PR'	}	,
  {	id:	219	,	name:	'Maua da Serra - PR'	}	,
  {	id:	220	,	name:	'Medianeira - PR'	}	,
  {	id:	221	,	name:	'Mercedes - PR'	}	,
  {	id:	222	,	name:	'Mirador - PR'	}	,
  {	id:	223	,	name:	'Miraselva - PR'	}	,
  {	id:	224	,	name:	'Missal - PR'	}	,
  {	id:	225	,	name:	'Moreira Sales - PR'	}	,
  {	id:	226	,	name:	'Morretes - PR'	}	,
  {	id:	227	,	name:	'Munhoz de Melo - PR'	}	,
  {	id:	228	,	name:	'Nossa Senhora das Gracas - PR'	}	,
  {	id:	229	,	name:	'Nova Alianca do Ivai - PR'	}	,
  {	id:	230	,	name:	'Nova America da Colina - PR'	}	,
  {	id:	231	,	name:	'Nova Aurora - PR'	}	,
  {	id:	232	,	name:	'Nova Cantu - PR'	}	,
  {	id:	233	,	name:	'Nova Esperanca do Sudoeste - PR'	}	,
  {	id:	234	,	name:	'Nova Esperanca - PR'	}	,
  {	id:	235	,	name:	'Nova Fatima - PR'	}	,
  {	id:	236	,	name:	'Nova Laranjeiras - PR'	}	,
  {	id:	237	,	name:	'Nova Londrina - PR'	}	,
  {	id:	238	,	name:	'Nova Olimpia - PR'	}	,
  {	id:	239	,	name:	'Nova Prata do Iguacu - PR'	}	,
  {	id:	240	,	name:	'Nova Santa Barbara - PR'	}	,
  {	id:	241	,	name:	'Nova Santa Rosa - PR'	}	,
  {	id:	242	,	name:	'Nova Tebas - PR'	}	,
  {	id:	243	,	name:	'Novo Itacolomi - PR'	}	,
  {	id:	244	,	name:	'Ortigueira - PR'	}	,
  {	id:	245	,	name:	'Ourizona - PR'	}	,
  {	id:	246	,	name:	'Ouro Verde do Oeste - PR'	}	,
  {	id:	247	,	name:	'Paicandu - PR'	}	,
  {	id:	248	,	name:	'Palmas - PR'	}	,
  {	id:	249	,	name:	'Palmeira - PR'	}	,
  {	id:	250	,	name:	'Palmital - PR'	}	,
  {	id:	251	,	name:	'Palotina - PR'	}	,
  {	id:	252	,	name:	'Paraiso do Norte - PR'	}	,
  {	id:	253	,	name:	'Paranacity - PR'	}	,
  {	id:	254	,	name:	'Paranagua - PR'	}	,
  {	id:	255	,	name:	'Paranapoema - PR'	}	,
  {	id:	256	,	name:	'Paranavai - PR'	}	,
  {	id:	257	,	name:	'Pato Bragado - PR'	}	,
  {	id:	258	,	name:	'Pato Branco - PR'	}	,
  {	id:	259	,	name:	'Paula Freitas - PR'	}	,
  {	id:	260	,	name:	'Paulo Frontin - PR'	}	,
  {	id:	261	,	name:	'Peabiru - PR'	}	,
  {	id:	262	,	name:	'Perobal - PR'	}	,
  {	id:	263	,	name:	'Perola d Oeste - PR'	}	,
  {	id:	264	,	name:	'Perola - PR'	}	,
  {	id:	265	,	name:	'Pien - PR'	}	,
  {	id:	266	,	name:	'Pinhais - PR'	}	,
  {	id:	267	,	name:	'Pinhal de Sao Bento - PR'	}	,
  {	id:	268	,	name:	'Pinhalao - PR'	}	,
  {	id:	269	,	name:	'Pinhao - PR'	}	,
  {	id:	270	,	name:	'Pirai do Sul - PR'	}	,
  {	id:	271	,	name:	'Piraquara - PR'	}	,
  {	id:	272	,	name:	'Pitanga - PR'	}	,
  {	id:	273	,	name:	'Pitangueiras - PR'	}	,
  {	id:	274	,	name:	'Planaltina do Parana - PR'	}	,
  {	id:	275	,	name:	'Planalto - PR'	}	,
  {	id:	276	,	name:	'Ponta Grossa - PR'	}	,
  {	id:	277	,	name:	'Pontal do Parana - PR'	}	,
  {	id:	278	,	name:	'Porecatu - PR'	}	,
  {	id:	279	,	name:	'Porto Amazonas - PR'	}	,
  {	id:	280	,	name:	'Porto Barreiro - PR'	}	,
  {	id:	281	,	name:	'Porto Rico - PR'	}	,
  {	id:	282	,	name:	'Porto Vitoria - PR'	}	,
  {	id:	283	,	name:	'Prado Ferreira - PR'	}	,
  {	id:	284	,	name:	'Pranchita - PR'	}	,
  {	id:	285	,	name:	'Presidente Castelo Branco - PR'	}	,
  {	id:	286	,	name:	'Primeiro de Maio - PR'	}	,
  {	id:	287	,	name:	'Prudentopolis - PR'	}	,
  {	id:	288	,	name:	'Quarto Centenario - PR'	}	,
  {	id:	289	,	name:	'Quatigua - PR'	}	,
  {	id:	290	,	name:	'Quatro Barras - PR'	}	,
  {	id:	291	,	name:	'Quatro Pontes - PR'	}	,
  {	id:	292	,	name:	'Quedas do Iguacu - PR'	}	,
  {	id:	293	,	name:	'Querencia do Norte - PR'	}	,
  {	id:	294	,	name:	'Quinta do Sol - PR'	}	,
  {	id:	295	,	name:	'Quitandinha - PR'	}	,
  {	id:	296	,	name:	'Ramilandia - PR'	}	,
  {	id:	297	,	name:	'Rancho Alegre d Oeste - PR'	}	,
  {	id:	298	,	name:	'Rancho Alegre - PR'	}	,
  {	id:	299	,	name:	'Realeza - PR'	}	,
  {	id:	300	,	name:	'Reboucas - PR'	}	,
  {	id:	301	,	name:	'Renascenca - PR'	}	,
  {	id:	302	,	name:	'Reserva do Iguacu - PR'	}	,
  {	id:	303	,	name:	'Reserva - PR'	}	,
  {	id:	304	,	name:	'Ribeirao Claro - PR'	}	,
  {	id:	305	,	name:	'Ribeirao do Pinhal - PR'	}	,
  {	id:	306	,	name:	'Rio Azul - PR'	}	,
  {	id:	307	,	name:	'Rio Bom - PR'	}	,
  {	id:	308	,	name:	'Rio Bonito do Iguacu - PR'	}	,
  {	id:	309	,	name:	'Rio Branco do Ivai - PR'	}	,
  {	id:	310	,	name:	'Rio Branco do Sul - PR'	}	,
  {	id:	311	,	name:	'Rio Negro - PR'	}	,
  {	id:	312	,	name:	'Rolandia - PR'	}	,
  {	id:	313	,	name:	'Roncador - PR'	}	,
  {	id:	314	,	name:	'Rondon - PR'	}	,
  {	id:	315	,	name:	'Rosario do Ivai - PR'	}	,
  {	id:	316	,	name:	'Sabaudia - PR'	}	,
  {	id:	317	,	name:	'Salgado Filho - PR'	}	,
  {	id:	318	,	name:	'Salto do Itarare - PR'	}	,
  {	id:	319	,	name:	'Salto do Lontra - PR'	}	,
  {	id:	320	,	name:	'Santa Amelia - PR'	}	,
  {	id:	321	,	name:	'Santa Cecilia do Pavao - PR'	}	,
  {	id:	322	,	name:	'Santa Cruz de Monte Castelo - PR'	}	,
  {	id:	323	,	name:	'Santa Fe - PR'	}	,
  {	id:	324	,	name:	'Santa Helena - PR'	}	,
  {	id:	325	,	name:	'Santa Ines - PR'	}	,
  {	id:	326	,	name:	'Santa Isabel do Ivai - PR'	}	,
  {	id:	327	,	name:	'Santa Izabel do Oeste - PR'	}	,
  {	id:	328	,	name:	'Santa Lucia - PR'	}	,
  {	id:	329	,	name:	'Santa Maria do Oeste - PR'	}	,
  {	id:	330	,	name:	'Santa Mariana - PR'	}	,
  {	id:	331	,	name:	'Santa Monica - PR'	}	,
  {	id:	332	,	name:	'Santa Tereza do Oeste - PR'	}	,
  {	id:	333	,	name:	'Santa Terezinha de Itaipu - PR'	}	,
  {	id:	334	,	name:	'Santana do Itarare - PR'	}	,
  {	id:	335	,	name:	'Santo Antonio da Platina - PR'	}	,
  {	id:	336	,	name:	'Santo Antonio do Caiua - PR'	}	,
  {	id:	337	,	name:	'Santo Antonio do Paraiso - PR'	}	,
  {	id:	338	,	name:	'Santo Antonio do Sudoeste - PR'	}	,
  {	id:	339	,	name:	'Santo Inacio - PR'	}	,
  {	id:	340	,	name:	'Sao Carlos do Ivai - PR'	}	,
  {	id:	341	,	name:	'Sao Jeronimo da Serra - PR'	}	,
  {	id:	342	,	name:	'Sao Joao do Caiua - PR'	}	,
  {	id:	343	,	name:	'Sao Joao do Ivai - PR'	}	,
  {	id:	344	,	name:	'Sao Joao do Triunfo - PR'	}	,
  {	id:	345	,	name:	'Sao Joao - PR'	}	,
  {	id:	346	,	name:	'Sao Jorge d Oeste - PR'	}	,
  {	id:	347	,	name:	'Sao Jorge do Ivai - PR'	}	,
  {	id:	348	,	name:	'Sao Jorge do Patrocinio - PR'	}	,
  {	id:	349	,	name:	'Sao Jose da Boa Vista - PR'	}	,
  {	id:	350	,	name:	'Sao Jose das Palmeiras - PR'	}	,
  {	id:	351	,	name:	'Sao Jose dos Pinhais - PR'	}	,
  {	id:	352	,	name:	'Sao Manoel do Parana - PR'	}	,
  {	id:	353	,	name:	'Sao Mateus do Sul - PR'	}	,
  {	id:	354	,	name:	'Sao Miguel do Iguacu - PR'	}	,
  {	id:	355	,	name:	'Sao Pedro do Iguacu - PR'	}	,
  {	id:	356	,	name:	'Sao Pedro do Ivai - PR'	}	,
  {	id:	357	,	name:	'Sao Pedro do Parana - PR'	}	,
  {	id:	358	,	name:	'Sao Sebastiao da Amoreira - PR'	}	,
  {	id:	359	,	name:	'Sao Tome - PR'	}	,
  {	id:	360	,	name:	'Sapopema - PR'	}	,
  {	id:	361	,	name:	'Sarandi - PR'	}	,
  {	id:	362	,	name:	'Saudade do Iguacu - PR'	}	,
  {	id:	363	,	name:	'Senges - PR'	}	,
  {	id:	364	,	name:	'Serranopolis do Iguacu - PR'	}	,
  {	id:	365	,	name:	'Sertaneja - PR'	}	,
  {	id:	366	,	name:	'Sertanopolis - PR'	}	,
  {	id:	367	,	name:	'Siqueira Campos - PR'	}	,
  {	id:	368	,	name:	'Sulina - PR'	}	,
  {	id:	369	,	name:	'Tamarana - PR'	}	,
  {	id:	370	,	name:	'Tamboara - PR'	}	,
  {	id:	371	,	name:	'Tapejara - PR'	}	,
  {	id:	372	,	name:	'Tapira - PR'	}	,
  {	id:	373	,	name:	'Teixeira Soares - PR'	}	,
  {	id:	374	,	name:	'Telemaco Borba - PR'	}	,
  {	id:	375	,	name:	'Terra Boa - PR'	}	,
  {	id:	376	,	name:	'Terra Rica - PR'	}	,
  {	id:	377	,	name:	'Terra Roxa - PR'	}	,
  {	id:	378	,	name:	'Tibagi - PR'	}	,
  {	id:	379	,	name:	'Tijucas do Sul - PR'	}	,
  {	id:	380	,	name:	'Toledo - PR'	}	,
  {	id:	381	,	name:	'Tomazina - PR'	}	,
  {	id:	382	,	name:	'Tres Barras do Parana - PR'	}	,
  {	id:	383	,	name:	'Tunas do Parana - PR'	}	,
  {	id:	384	,	name:	'Tuneiras do Oeste - PR'	}	,
  {	id:	385	,	name:	'Tupassi - PR'	}	,
  {	id:	386	,	name:	'Turvo - PR'	}	,
  {	id:	387	,	name:	'Ubirata - PR'	}	,
  {	id:	388	,	name:	'Umuarama - PR'	}	,
  {	id:	389	,	name:	'Uniao da Vitoria - PR'	}	,
  {	id:	390	,	name:	'Uniflor - PR'	}	,
  {	id:	391	,	name:	'Urai - PR'	}	,
  {	id:	392	,	name:	'Ventania - PR'	}	,
  {	id:	393	,	name:	'Vera Cruz do Oeste - PR'	}	,
  {	id:	394	,	name:	'Vere - PR'	}	,
  {	id:	395	,	name:	'Vila Alta - PR'	}	,
  {	id:	396	,	name:	'Virmond - PR'	}	,
  {	id:	397	,	name:	'Vitorino - PR'	}	,
  {	id:	398	,	name:	'Wenceslau Braz - PR'	}	,
  {	id:	399	,	name:	'Xambre - PR'	}	,  
];  